import { useState, useEffect } from 'react';

const API_BASE = import.meta.env.VITE_API_URL || '';
const GH_TOKEN = import.meta.env.VITE_GITHUB_TOKEN || '';
const GH_OWNER = import.meta.env.VITE_GITHUB_PROJECT_OWNER || 'thisisrober';
const GH_PROJECT = Number(import.meta.env.VITE_GITHUB_PROJECT_NUMBER || '3');

/* Static snapshot generated by `uv run python scripts/fetch_roadmap.py`.
   The bundle is deployed both at the root of nova.thisisrober.es and under
   /projects/nova-agent on the portfolio, so resolve the mount point the same
   way main.tsx derives the router basename. */
const PORTFOLIO_PREFIX = '/projects/nova-agent';
const SNAPSHOT_URL = `${
  window.location.pathname.startsWith(PORTFOLIO_PREFIX) ? `${PORTFOLIO_PREFIX}/` : '/'
}roadmap.json`;

/* ─── Types ─── */

export interface RoadmapLabel {
  name: string;
  color: string;
}

export interface RoadmapIssue {
  title: string;
  number: number | null;
  url: string | null;
  state: string | null;
  status: string | null;
  priority: string | null;
  size: string | null;
  labels: RoadmapLabel[];
}

export interface RoadmapIteration {
  id: string;
  title: string;
  start_date: string | null;
  /** Length in days, as configured on the GitHub board. */
  duration: number | null;
  /** Inclusive last day (start_date + duration - 1). */
  end_date: string | null;
  items: RoadmapIssue[];
}

export interface RoadmapData {
  project_title: string;
  project_description: string | null;
  project_url: string;
  iterations: RoadmapIteration[];
  backlog: RoadmapIssue[];
  /** ISO timestamp, only present on the static snapshot. */
  generated_at?: string;
}

/* ─── GraphQL query (same as backend) ─── */

const PROJECT_QUERY = `
query($owner: String!, $number: Int!) {
  user(login: $owner) {
    projectV2(number: $number) {
      title
      shortDescription
      url
      fields(first: 50) {
        nodes {
          ... on ProjectV2IterationField {
            id
            name
            configuration {
              iterations { id title startDate duration }
              completedIterations { id title startDate duration }
            }
          }
        }
      }
      items(first: 100) {
        nodes {
          fieldValues(first: 50) {
            nodes {
              ... on ProjectV2ItemFieldSingleSelectValue {
                name
                field { ... on ProjectV2SingleSelectField { name } }
              }
              ... on ProjectV2ItemFieldIterationValue {
                title
                startDate
                duration
                iterationId
                field { ... on ProjectV2IterationField { name } }
              }
            }
          }
          content {
            ... on Issue {
              title
              number
              url
              state
              labels(first: 10) {
                nodes { name color }
              }
            }
            ... on DraftIssue {
              title
            }
          }
        }
      }
    }
  }
}`;

/* ─── Helpers ─── */

/**
 * Inclusive last day of an iteration.
 *
 * GitHub stores a start day plus a duration in days, so an iteration starting
 * 2026-07-01 with duration 92 ends on 2026-09-30 — not 2026-10-01, which is
 * the first day of the next one.
 */
export function iterationEndDate(
  startDate: string | null,
  duration: number | null,
): string | null {
  if (!startDate || !duration) return null;
  const start = new Date(`${startDate}T00:00:00Z`);
  if (Number.isNaN(start.getTime())) return null;
  const end = new Date(start.getTime() + (duration - 1) * 86400000);
  return end.toISOString().slice(0, 10);
}

function buildIteration(
  id: string,
  title: string,
  startDate: string | null,
  duration: number | null,
): RoadmapIteration {
  return {
    id,
    title,
    start_date: startDate,
    duration,
    end_date: iterationEndDate(startDate, duration),
    items: [],
  };
}

/** A response is only usable if it is actually JSON — an SPA `try_files`
 *  fallback happily answers 200 with index.html. */
async function readJson(res: Response): Promise<unknown | null> {
  if (!res.ok) return null;
  const contentType = res.headers.get('content-type') || '';
  if (!contentType.includes('application/json')) return null;
  try {
    return await res.json();
  } catch {
    return null;
  }
}

function isRoadmapData(value: unknown): value is RoadmapData {
  const v = value as RoadmapData | null;
  return !!v && Array.isArray(v.iterations) && Array.isArray(v.backlog);
}

/* ─── Parse GraphQL response into RoadmapData ─── */

function parseGraphQLResponse(data: Record<string, unknown>): RoadmapData {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const project = (data as any).data.user.projectV2;

  // Build iteration map
  const iterationMap = new Map<string, RoadmapIteration>();
  for (const field of project.fields.nodes) {
    if (!field?.configuration) continue;
    const allIterations = [
      ...(field.configuration.iterations || []),
      ...(field.configuration.completedIterations || []),
    ];
    for (const it of allIterations) {
      iterationMap.set(it.id, buildIteration(it.id, it.title, it.startDate ?? null, it.duration ?? null));
    }
  }

  const backlog: RoadmapIssue[] = [];

  for (const item of project.items.nodes) {
    const content = item?.content;
    if (!content?.title) continue;

    const labels: RoadmapLabel[] = (content.labels?.nodes || []).map(
      (l: { name: string; color: string }) => ({ name: l.name, color: l.color }),
    );

    let status: string | null = null;
    let priority: string | null = null;
    let size: string | null = null;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let iterationValue: any = null;

    for (const fv of item.fieldValues?.nodes || []) {
      if (!fv) continue;
      // Iteration values are identified by their payload rather than by the
      // field's name: boards are free to rename "Iteration" to "Sprint" etc.
      if (fv.iterationId) {
        iterationValue = fv;
        continue;
      }
      const fieldName = fv.field?.name || '';
      if (fieldName === 'Status') status = fv.name ?? null;
      else if (fieldName === 'Priority') priority = fv.name ?? null;
      else if (fieldName === 'Size') size = fv.name ?? null;
    }

    const issue: RoadmapIssue = {
      title: content.title,
      number: content.number ?? null,
      url: content.url ?? null,
      state: content.state ?? null,
      status,
      priority,
      size,
      labels,
    };

    if (!iterationValue) {
      backlog.push(issue);
      continue;
    }

    const iterationId: string = iterationValue.iterationId;
    if (!iterationMap.has(iterationId)) {
      // Item points at an iteration the field configuration no longer lists;
      // rebuild it from the value instead of demoting the item to the backlog.
      iterationMap.set(
        iterationId,
        buildIteration(
          iterationId,
          iterationValue.title ?? '',
          iterationValue.startDate ?? null,
          iterationValue.duration ?? null,
        ),
      );
    }
    iterationMap.get(iterationId)!.items.push(issue);
  }

  const sortedIterations = Array.from(iterationMap.values()).sort((a, b) => {
    const byDate = (a.start_date || '').localeCompare(b.start_date || '');
    return byDate !== 0 ? byDate : a.title.localeCompare(b.title);
  });

  return {
    project_title: project.title || '',
    project_description: project.shortDescription ?? null,
    project_url: project.url || '',
    iterations: sortedIterations,
    backlog,
  };
}

/* ─── GitHub REST API fallback types ─── */

interface GitHubRESTIssue {
  title: string;
  number: number;
  html_url: string;
  state: string;
  labels: { name: string; color: string }[];
  pull_request?: unknown;
}

/* ─── Hook ─── */

export function useRoadmap() {
  const [data, setData] = useState<RoadmapData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function fetchRoadmap() {
      setLoading(true);
      setError(null);

      // ── Layer 1: Live backend proxy (full Projects V2 data) ──
      try {
        const res = await fetch(`${API_BASE}/api/v1/github/roadmap`);
        const json = await readJson(res);
        if (isRoadmapData(json)) {
          if (!cancelled) { setData(json); setLoading(false); }
          return;
        }
      } catch {
        // Backend not available, try next layer
      }

      // ── Layer 2: Static snapshot baked in at build time ──
      // This is what production serves: the site is deployed as a static
      // bundle with no API behind it.
      try {
        const res = await fetch(SNAPSHOT_URL, { cache: 'no-cache' });
        const json = await readJson(res);
        if (isRoadmapData(json)) {
          if (!cancelled) { setData(json); setLoading(false); }
          return;
        }
      } catch {
        // No snapshot available, try next layer
      }

      // ── Layer 3: GitHub GraphQL directly (dev only) ──
      // VITE_* values are inlined into the bundle, so a token here would be
      // published with the site. Restricted to dev builds on purpose.
      if (GH_TOKEN && import.meta.env.DEV) {
        try {
          const res = await fetch('https://api.github.com/graphql', {
            method: 'POST',
            headers: {
              Authorization: `Bearer ${GH_TOKEN}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              query: PROJECT_QUERY,
              variables: { owner: GH_OWNER, number: GH_PROJECT },
            }),
          });
          if (res.ok) {
            const json = await res.json();
            if (!json.errors) {
              const parsed = parseGraphQLResponse(json);
              if (!cancelled) { setData(parsed); setLoading(false); }
              return;
            }
          }
        } catch {
          // GraphQL call failed, try next layer
        }
      }

      // ── Layer 4: Public REST API (no auth, no iteration data) ──
      try {
        const res = await fetch(
          `https://api.github.com/repos/${GH_OWNER}/nova-agent/issues?state=all&per_page=100`,
          { headers: { Accept: 'application/vnd.github.v3+json' } },
        );
        if (!res.ok) throw new Error(`GitHub API: ${res.status}`);
        const issues: GitHubRESTIssue[] = await res.json();

        const realIssues = issues.filter((i) => !i.pull_request);

        const mappedIssues: RoadmapIssue[] = realIssues.map((i) => ({
          title: i.title,
          number: i.number,
          url: i.html_url,
          state: i.state,
          // The REST API has no Status column; approximate it with the board's
          // vocabulary so the badges stay consistent across data sources.
          status: i.state === 'open' ? 'Backlog' : 'Done',
          priority: null,
          size: null,
          labels: i.labels.map((l) => ({ name: l.name, color: l.color })),
        }));

        if (!cancelled) {
          setData({
            project_title: 'NOVA — Neural Orchestration & Virtual Agent',
            project_description: null,
            project_url: `https://github.com/users/${GH_OWNER}/projects/${GH_PROJECT}/views/1`,
            iterations: [],
            backlog: mappedIssues,
          });
          setLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load roadmap');
          setLoading(false);
        }
      }
    }

    fetchRoadmap();
    return () => { cancelled = true; };
  }, []);

  return { data, loading, error };
}
