apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nova

resources:
  - namespace.yaml
  - vllm-pvc.yaml
  - vllm-deployment.yaml
  - vllm-service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
